### ISSUE TITLE
Looking for new owners

### ISSUE THREAD

**Issue by Deewiant** [arybczak/list-tries#13]
Unfortunately I'm fairly out of touch with the Haskell community these days and don't really have the time or interest to maintain either https://github.com/Deewiant/list-tries or https://github.com/Deewiant/glob properly. For example, I used to be proactive about following the Travis CI notifications about GHC HEAD failing and fixing issues before the next GHC release comes out, but these days I'm letting things languish and only react when someone opens an issue or PR about it. Let alone actually doing more development than the minimal compatibility fixes.

So I'm facing the facts and willing to relinquish ownership of both repos to someone more active. If you're interested, let me know.

Equivalent issue for Glob: https://github.com/Deewiant/glob/issues/36

**Comment by arybczak** [comment]
Sure, I can take over this package :+1:

**Comment by Deewiant** [comment]
Great, thanks a lot!

Any preferences on what to do with this repo? There's the issue/PR history that you might not want to lose, including the two currently open issues (other than this one). I could transfer it to your GitHub account but I think (from reading https://help.github.com/en/github/administering-a-repository/transferring-a-repository) that you'd need to delete your fork first. Alternatively I could create an organization and move this to `list-tries/list-tries`. Or I can just add a note in this repo pointing to wherever you want.

Meanwhile I've granted you Hackage maintainership.

I think those two things are all that's needed, right? You can then upload a new version with updated URLs and whatnot.

**Comment by arybczak** [comment]
Yes, these two are enough, thanks!

I deleted my fork, so you can transfer the repo to my account if that's okay with you.

**Comment by Deewiant** [comment]
Done, you just need to approve.

**Comment by arybczak** [comment]
Thanks :)
